common/common/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/store/urls.py
from django.urls import path
from .views import save_order, ProductListView, ProductDetailView, CategoryDetailView, index

urlpatterns = [
    path('products/', ProductListView.as_view(), name='product_list_url'),
    path('products/<int:pk>/', ProductDetailView.as_view(), name='product_detail_url'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail_url'),
    path('save_order/', save_order),
    path('', index)
]

common/store/models.py
from django.db import models
from django.shortcuts import reverse

class Product(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    info = models.TextField(blank=True)
    price = models.IntegerField()
    color = models.ForeignKey("Color", on_delete=models.PROTECT)
    storage = models.IntegerField()
    categories = models.ManyToManyField("Category", blank=True, related_name="products")
    image = models.ImageField(upload_to="images/", default="images/default.png")


    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse("product_detail_url", kwargs={'pk': self.pk})

    class Meta:
        ordering = ['price']


class Category(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name_plural = "Categories"



class Color(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.title
    

class Order(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    product = models.ForeignKey(Product, on_delete=models.PROTECT)

    def __str__(self) -> str:
        return self.name

common/store/views.py
from typing import Any, Dict
from django.shortcuts import render
from .models import Product, Order, Category
from django.views.generic import ListView, DetailView
from .util import CategoryListMixin



class ProductListView(CategoryListMixin, ListView):
    model = Product

    def get_queryset(self):
        search_query = self.request.GET.get("search", None)
        if search_query:
            return self.model.objects.filter(title__icontains=search_query)
        return self.model.objects.all()
    


    

"""
def product_list(request):
    search_query = request.GET.get('search', None)
    if search_query:
        product_list = Product.objects.filter(title__icontains=search_query)
    else:
        product_list = Product.objects.all()
    return render(request, "store/product_list.html", context={'product_list' : product_list})
"""


class ProductDetailView(DetailView, CategoryListMixin):
    model = Product


"""
def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    return render(request, "store/product_detail.html", context={'product': product})
"""


class CategoryDetailView(DetailView, CategoryListMixin):
    model = Category


"""
def category_detail(request, pk):
    category = Category.objects.get(pk=pk)
    return render(request, "store/category_detail.html", context={'category': category})
"""


def save_order(request):
    product = Product.objects.get(pk=request.POST["product_id"])
    order = Order()
    order.name = request.POST["user_name"]
    order.email = request.POST["user_email"]
    order.product = product
    order.save()

    return render(
        request,
        "store/save_order.html",
        context={"product": product, "name": request.POST["user_name"]},
    )



def index(request):
    #create
    #p = Product(title='ICL', price=1200, color_id=1, storage=256)
    #p.save()
    
    #p = Product.objects.create(title='HP', price=100, color_id=2, storage=256)
    
    #update
    #p = Product.objects.get(pk=9)
    #p.price += 10
    #p.save()

    #Product.objects.filter(pk = 9).update(price = 160)
    #p = Product.objects.get(pk=9)
    
    #destroy
    #Product.objects.get(pk=9).delete()
    #p = Product.objects.all()
    
    #get 
    #p = Product.objects.filter(title='ICL')


    #print(p)
    return render(request, 'store/product_list.html')

common/store/templates/store/category_detail.html
{% extends "store/index.html" %}


{% block content %}


<div class="row justify-content-center">
    {% for product in category.products.all %}
        {% include "store/includes/card.html" %}
    {% endfor %}
</div>

{% endblock %}

common/store/templates/store/includes/card.html
<div class="card col-lg-4 col-md-6 col-sm-12">
    <img src="{{ product.image.url }}"
        class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{product.title}}</h5>
        <p class="card-text">{{product.info|truncatewords:15}}</p>
        <p class="card-text">Price: {{product.price}}$</p>

        <ul class="list-group mb-3">
            <li class="list-group-item text-capitalize">{{product.color}}</li>
            <li class="list-group-item">{{product.storage}}</li>
        </ul>
        <a href="{% url 'product_detail_url' pk=product.pk %}" class="btn btn-primary">Read more</a>

    </div>
</div>

common/store/templates/store/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
  
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>
  

  <title>
    {% block title %}
    home
    {% endblock %}
  </title>
</head>

<body class="d-flex flex-column justify-content-between min-vh-100">
  <header class="fixed-top">
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark ">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Store</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'product_list_url' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu">
                {% for el in category_list %}
                <li class="ps-4 text-capitalize"><a class="dropdown-item" href="{% url 'category_detail_url' pk=el.pk %}">{{el.title}}</a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
          <form class="d-flex" role="search" action="{% url 'product_list_url' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
  </header>

  <main class="mt-5 pt-2">
    <div class="container-fluid">
      {% block content %}
      content
      {% endblock %}
    </div>
  </main>

  <footer class="d-flex justify-content-center align-items-center bg-dark text-white footer">

    <span>Contacts: 89999999999</span>

  </footer>
</body>

</html>

common/store/templates/store/product_detail.html
{% extends "store/index.html" %}

{% block title %}
    {{product.title}}
{% endblock %}


{% block content %}


<div class="card">
    <img src="{{ product.image.url }}"
        class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{product.title}}</h5>
        <p class="card-text">{{product.info}}</p>
        <p class="card-text">Price: {{product.price}}</p>

        <ul class="list-group mb-3">
            <li class="list-group-item text-capitalize">{{product.color}}</li>
            <li class="list-group-item">{{product.storage}}</li>
            {% for category in product.categories.all %}
                <li class="list-group-item">{{category.title}}</li>
            {% endfor %}
        </ul>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Buy now
        </button>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Окно для заказа</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            
            <div class="modal-body">
                <form action="/save_order" method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <input class="form-control me-2" type="text" placeholder="Name" name="user_name" required>
                    </div>
                    <div class="mb-3">
                        <input class="form-control me-2" type="email" placeholder="Email" name="user_email" required>
                    </div>
                    <input type="hidden" value="{{product.pk}}" name="product_id" >
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-secondary">Отправить</button>
                    </div>
                </form>
            </div>

        </div>
    </div>      
</div>



{%endblock%}

common/store/templates/store/product_list.html
{% extends "store/index.html" %}


{% block content %}


<div class="row justify-content-center">
    {% for product in product_list %}
        {% include "store/includes/card.html" %}
    {% endfor %}
</div>

{% endblock %}

common/store/templates/store/save_order.html
{% extends "store/index.html" %}

{% block content %}

    <h1 class="mt-3">Привет, {{name}}. Заказ на {{product.title}} по цене {{product.price}}$ обработан!</h1>

{% endblock %}